### PR TITLE
Fix dogstatd v5 thread leak

### PR DESCRIPTION
**Pull request by donbobka**
`dogstatd` gem recently was updated and introduced a new threading model that leads to thread leak with some implementations.

Recommendations are following https://github.com/DataDog/dogstatsd-ruby#migrating-from-v4x-to-v5x.

In my PR I implemented:
1. close dogstatd client with `close` method
2. use v4 single thread model using `single_thread` option if dogstatd version >= 5.2. I tried to make it backward compatible with v4 but if we ok to drop v4, then code can be much simpler + we can rely on dogstatd batching

https://github.com/DataDog/dd-trace-rb/issues/1491
https://github.com/DataDog/dogstatsd-ruby/issues/182

### CODE REVIEW

**Comment by Envek** [comment]
Hey, thank you for the pull request!

I'm personally fine with bumping the requirement to use latest Datadog client (`~> 5.2`).

@dmshvetsov, any thoughts?

**Comment by dmshvetsov** [comment]
Hi @donbobka , thank you for the PR and sorry for the long response. I will review this PR this week.

**Comment by dmshvetsov** [comment]
@Envek agree.

@donbobka would you mind updating the dogstatsd-ruby requirement to `-> 5.2` and remove the code that checks the dogstatd gem version?

**Comment by dmshvetsov** [comment]
@donbobka I saw you've pushed some changes 🙌 . Is it ready to be merged?

**Comment by dmshvetsov** [comment]
@donbobka thank you! 🙏

**Comment by dmshvetsov** [comment]
@donbobka a [0.3.6 release candidate version](https://rubygems.org/gems/yabeda-datadog/versions/0.3.6.rc1) of yabeda-datadog has been released. I do not have a project to test it against. If you can use the rc version and provide feedback that would be extremely helpful.

**Comment by donbobka** [comment]
@dmshvetsov We deployed rc version last week and there are no problems so far

**Comment by dmshvetsov** [comment]
great news, thanks @donbobka

**Comment by dmshvetsov** [comment]
0.3.6 with support for dogstatsd 5 has been released https://rubygems.org/gems/yabeda-datadog/versions/0.3.6 🎉

**Pull request merged**
